screen_track/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('screentrackapp.urls')),
    path('user/', include('user.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
urlpatterns += staticfiles_urlpatterns()

screentrackapp/urls.py
from django.urls import path
from . import views

app_name = 'screentrackapp'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('<slug:pk>/', views.UserProfileView.as_view(), name='profile'),
    path('<slug:pk>/edit/', views.EditProfileView.as_view(), name='edit-profile'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ScreenTrack- {% block page_title%}{%endblock%} </title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,300;0,400;0,500;0,600;0,700;0,900;1,100;1,400;1,500;1,600;1,700;1,900&display=swap" rel="stylesheet">
    
    <link rel="stylesheet" href="{% static 'css/base.css' %}">

    {% block styles %}{% endblock %}
</head>
<body>
    <nav>
        <div class="logo">
            <a href="{% url 'screentrackapp:home' %}">ScreenTrack</a>
        </div>

        
        <div class="nav-items">
            <a href="{% url 'screentrackapp:home' %}" class="nav-link {% if page_title == 'Home' %} active {% endif %}">Home</a>
            {% if user.is_authenticated %}
                <a href="" class="nav-link {% if page_title == 'History' %} active {% endif %}">History</a>
                <div class="profile">
                    <div class="profile-container">
                        <div class="profile-picture">
                            <img src="{{ user.profile_pic.url }}" alt="profile-pic">
                        </div>
                        <p class="nav-link {% if page_title == 'Profile' %} active {% endif %}">Profile</p>
                    </div>

                    <div class="profile-settings">
                        <a href="{% url 'user:profile' user.id %}" class="{% if page_title == 'Profile' %} active {% endif %}">View Profile</a>
                        <a href="{% url 'user:edit-profile' user.id %}" class="{% if page_title == 'Edit Profile' %} active {% endif %}">Edit Profile</a>
                        <a href="" class="{% if page_title == 'Change Profile Picture' %} active {% endif %}">Change Profile Picture</a>
                        <a href="" class="{% if page_title == 'Change Password' %} active {% endif %}">Change Password</a>
                    </div>
                </div>
                <a href="{% url 'user:logout' %}" class="nav-link {% if page_title == 'Logout' %} active {% endif %}">Logout</a>
                
                {% else %}
                    <a href="{% url 'user:login' %}" class="nav-link {% if page_title == 'Login' %} active {% endif %}">Login</a>
                    <a href="{% url 'user:signup' %}" class="nav-link {% if page_title == 'Sign Up' %} active {% endif %}">Sign Up</a>
                {% endif %}
            </div>
        </nav>
        
    {% include 'constants/messages.html' %}

    <main>
        {% block main %}{% endblock %}
    </main>

    <footer>
        <p>&copy; {{ year }}. ScreenTrack</p>
    </footer>

    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>

    <script>
        var dropDownButton = document.querySelector('.profile');
        var dropDownItems = document.querySelector('.profile-settings')

        function openDropDown() {
            dropDownItems.style.display = 'block';
        }

        function closeDropDown() {
            dropDownItems.style.display = 'none';
        }

        dropDownButton.addEventListener('mouseover', openDropDown)
        dropDownButton.addEventListener('mouseout', closeDropDown)
    </script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block page_title%}Home{%endblock%}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block main %}
    {% if user.is_authenticated %}
        <section id="home-section">
            <div class="home-content">
                    {% if apps %}
                        <h1>Open Applications</h1>
                        <div class="open-apps">
                            {% for app in apps %}
                                <div class="app-container">
                                    <h3>{{ app }}</h3>
                                    <p>Screen Time- </p>
                                </div>
                            {% endfor %}
                        </div>
                    {% else %}
                        <p>No apps are open on your system</p>
                    {% endif %}
            </div>
        
            <div class="cpu-data">
                <p><b>CPU Usage:</b> <span id="cpu-percent">{{ cpu_percent }}%</span></p>
                <p><b>No of CPUs:</b> {{ cpu_count }}</p>
                <p><b>Min CPU Frequency:</b> {{ cpu_frequency.min }} MHz</p>
                <p><b>Current CPU Frequency:</b> {{ cpu_frequency.current }} MHz</p>
                <p><b>Max CPU Frequency:</b> {{ cpu_frequency.max }} MHz</p>
            </div>
        </section>

        <section id="analysis-section">
            <h1>Screen Time Analysis</h1>
            <div class="analysis">

            </div>

        </section>

        <!-- <script src="{% static 'js/refresh_data.js' %}"></script> -->
        <script>
            setTimeout(function() {
                location.reload();
            }, 10000);
        </script>
    {% else%}
        <section id="home-section">
            <h1>You need to login to have access to this page</h1>
        </section>
    {% endif %}
{% endblock %}